### ISSUE TITLE
Support for WLED 0.13.1?

### ISSUE THREAD

**Issue by sofakng** [awawa-dev/WLED#6]
Has this been updated to WLED 0.13.1?

I know the README says this project won't be updated but I saw a few commits so I was wondering.

I like having the flexibility of WLED animations (and for diyHue) but also use HyperHDR with AWA protocol.

**Comment by awawa-dev** [comment]
Hi
You have v7 beta available (based on WLED 0.13.1) in the releases section:
 https://github.com/awawa-dev/HyperSerialWLED/releases
Please follow the instruction and set desired serial communication speed in WLED panel.

But WLED WLED 0.13.1 has some serious bugs like:

https://github.com/Aircoookie/WLED/issues/2698 
https://github.com/Aircoookie/WLED/issues/2618

Don't know if it affects HyperSerialWLED because I have rewritten whole part of the WLED serial communication and at least it works for me. You can also test it and let me know about the result.

**Comment by MattWestb** [comment]
WLED 0.13.3 s released but i dont knowing if its somthing new or fixed things that can being good for our systems.
https://github.com/Aircoookie/WLED/releases/tag/v0.13.3

**Comment by appleimperio** [comment]
I was hopping there's a way you can make it work with 0.13.3 too.

**Comment by Konnor378** [comment]
@awawa-dev Will there ever be an update to wled? I am using a remote hyperhdr server with a wemos d1 mini with standard wled. I realize that my configuration using wifi is not the best and not as fast as the usb solution for ambilight, but this solution has cut my costs many times over without buying a separate RPI and Tv-box since I have android tv built into my TV and since it is still being updated, I'm not ready to buy a separate TV-box for it. With standard wled unfortunately there are problems with a small but noticeable delay. I think your high speed protocol can solve my problem.

**Comment by fl0eb** [comment]
If someone is interested it created a pull request: https://github.com/awawa-dev/HyperSerialWLED/pull/8

Please make sure to apply the fix https://github.com/Aircoookie/WLED/pull/4142/commits/2264cc5d10aae1fff21bf34782a09ff5291c9c3d before compiling

**Comment by appleimperio** [comment]
@fl0eb did you got wled 14.4 working? if so can you explain the process of how to compile it or guide me in the right direction. I would love to try it. Thank You

**Comment by fl0eb** [comment]
Yeah, works fine for me._ I got tired of HomeAssistant complaining about the old version not being compatible.

The only real "effort" was to merge the code from 0.14.4 together with the HyperSerialWLED code.

For compilation I just used VSCode together with the PlatformIO Extension nothing fancy.
There should be plenty of guides available on how to use it, but you generally just have to execute the "Build: HTML and binary" task.

If you are lazy and trust random people on the internet, here are my binaries, which you should be able to flash OTA.
[HyperSerialWLED_0.14.4_fl0eb_BETA.zip](https://github.com/user-attachments/files/17237927/HyperSerialWLED_0.14.4_fl0eb_BETA.zip)

**Comment by MattWestb** [comment]
Thanks @fl0eb it works great on one D1 Mini !!!
Hope  some can  do one V20 docker image for HyperHDR (was making on PR for updating it but is not  being merged after many mounts).

**Comment by appleimperio** [comment]
@MattWestb I create a Hyper-HDR docker image you can try it if you want to https://hub.docker.com/r/nocturno/hyper-hdr

**Comment by appleimperio** [comment]
@fl0eb Thank You. I will give it a try

**Comment by Konnor378** [comment]
@fl0eb 
Hi. I don't quite understand what you did? Just combined the wled 14.4 code and hyperserialwled? And what are the advantages of such integration? It would make a lot of sense to integrate the awa protocol into wled. And so my standard wled 14.4 works quite well with the backlight for the TV via wifi.

**Comment by fl0eb** [comment]
> @fl0eb Hi. I don't quite understand what you did? Just combined the wled 14.4 code and hyperserialwled? And what are the advantages of such integration? It would make a lot of sense to integrate the awa protocol into wled. And so my standard wled 14.4 works quite well with the backlight for the TV via wifi.

HyperSerialWLED is a fork of WLED which replaces the native serial communication with a custom „awa“-protocol.
All I did, was merging the latest changes of WLED into awawa-devs modified WLED code.
So yes, it is WLED with awa protocol.

To make the awa protocol natively supported by WLED you would need to make some adjustments and create a pull request for aircookies repository. However I don’t know if HyperHDR and HyperionNG is enough of a reason to include another protocol natively.

HyperSerialESP32 is a more stable solution with less overhead. Using WLED together with HyperSerial is not recommended and not actively maintained.
The only reason I use this, is because I like to use the ambient light even if the TV is off and home assistant requires the new version.

**Comment by awawa-dev** [comment]
There is new release based on 0.14.0: https://github.com/awawa-dev/HyperSerialWLED/releases/tag/h0.14.0
Hopefully it will be enough for next few years.
From my short testing 0.14.4 is not stable on esp32 (dev) https://github.com/awawa-dev/HyperSerialWLED/pull/10
Beside versions above 0.14.0 could have problems with esp8266: https://github.com/Aircoookie/WLED/issues/3685
